language: python
matrix:
  include:
    - python: "3.6"
      dist: trusty
      sudo: true
    - python: "3.7"
      dist: xenial
      sudo: true

addons:
  postgresql: "9.6"

before_install:
  - pip install pipenv
  - npm install -g npm@"^6.4.0"

install:
  - pipenv install --dev --deploy
  
before_script:
  - black . --check --exclude node_modules/

script: 
  - pytest
