language: python
matrix:
  include:
    - python: "3.6"
      dist: trusty
      sudo: true
    - python: "3.7"
      dist: xenial
      sudo: true

addons:
  postgresql: "9.6"

before_install:
  - pip install pipenv

install:
  - pipenv install --dev

before_script:
  - psql -c 'create database beekeeping;' -U postgres
  - pipenv run python manage.py makemigrations
  - pipenv run python manage.py migrate
script: 
  - pipenv run python manage.py test
