# Generated by Django 2.1.7 on 2019-03-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiveTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive_name', models.CharField(max_length=200)),
                ('hive_key', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('edited_date', models.DateTimeField(verbose_name='date edited')),
                ('timeline_date', models.DateTimeField(verbose_name='timeline date')),
                ('brood_cells', models.IntegerField(default=0)),
                ('honey_racks', models.IntegerField(default=0)),
                ('hive_size', models.IntegerField(default=0)),
                ('queen_spotted', models.BooleanField()),
                ('pests_disease', models.BooleanField()),
                ('plant_life', models.BooleanField()),
            ],
        ),
    ]
