# Generated by Django 2.1.7 on 2019-04-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_auto_20190324_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_key', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='hivetimeline',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
