# Generated by Django 2.1.7 on 2019-04-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
